server:  
  port: ${PORT:2222}

spring:
  boot:
    admin:
      client:
        url:
        - http://localhost:1111
        
  application:
    name: account-service  
    

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
ribbon:
  eureka:
    enabled: true