eureka:
  client:
    serviceUrl:
         
      register-with-eureka: true
 
  
server:
  port: 8765
spring:
  application:
    name: album-service
  cloud:
       config:
         uri: http://localhost:8888f