  
server:
  port: 8085
spring:
  boot:
    admin:
      client:
        url: http://localhost:9999
  application:
    name: student-service
  cloud:
    consul:
      discovery:
        register: true
        service-name: student-service
      host: localhost
      port: 8500
  datasource:    url: jdbc:mysql://localhost:3306/spring_security
    username: root
    password: Sai@1234
    driver-class-name: com.mysql.jdbc.Driver  jpa:    hibernate:      ddl-auto: update
    show-sql: true